version: "3"
services:
  movies:
    container_name: movies
    build:
      dockerfile: ../movies/Dockerfile
      target: development
      context: ../movies # is it correct ??
    image: movies
    ports:
      - "3000:3000"
    networks: 
      - movies-network
    depends_on:
      - rabbitmq
    env_file:
      - ../movies/.env
    # volumes:
    #   - ../movies/:/usr/src/app
    #   - /usr/src/app/node_modules
    # command: npm run start:dev movies
    
  movies-graphql-microservice:
    container_name: movies-graphql-microservice
    build: 
      dockerfile: Dockerfile
      target: development
      context: .
    image: movies-graphql-microservice
    ports: 
      - 3001:3001
      - 9229:9229
    networks:
      - movies-network
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug:docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - movies-network

networks:
  movies-network:
    driver: bridge