version: "3"
services:
  movies-graphql-microservice:
    container_name: movies-graphql-microservice
    build: 
      dockerfile: Dockerfile
      target: development
      context: .
    image: movies-graphql-microservice
    ports: 
      - 3001:3001
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug:docker