name: Hello world CI

on:
  # push:
  #   branches: '**'
  # pull_request:
  #   branches: [main]
  [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm lint
      - run: npm tsc

  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm test
